---
- hosts: server1
  remote_user: ubuntu
  
  tasks:
    - name : Add ppa repository
      become: yes
      apt_repository: repo=ppa:ondrej/php
    
    - name: Install lamp stack
      become: yes
      apt:
        pkg:
          - apache2
          - mysql-server
          - php7.0
          - php7.0-mysql 
        state: present
        update_cache : yes
    - name: start apache server
      become: yes
      service:
        name: apache2
        state: started
        enabled: yes
    -  name: start mysql service
       become: yes
       service:
        name: mysql
        state: started
        enabled: yes
    -  name: create target directory
       file: path=/var/www/html state=directory mode=0755
    - name:  deploy index.html
      become: yes
      copy: 
        src: /etc/ansible/index/index.html
        dest: var/www/html/index.html
    - name:  deploy style.css
      become: yes
      copy: 
        src: /etc/ansible/index/style.css
        dest: var/www/html/style.css
    - name:  deploy assets
      become: yes
      copy: 
        src: /etc/ansible/index/puppy.jpg
        dest: var/www/html/puppy.jpg


